version: '3.8'

services:
  backend:
    build: .
    command: uvicorn cadastre.main:app --host 0.0.0.0 --reload
    volumes:
      - ./cadastre:/app/cadastre
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  db_value:
